version: "3.7"

services:
    oracle_xe:
        container_name: oraclexe
        image: container-registry.oracle.com/database/express:21.3.0-xe
        hostname: database
        ports:
            - "1521:1521"
            - "5500:5500"
        networks:
            - apex-network
        volumes:
            - db-volume:/opt/oracle/oradata
        environment:
            - ORACLE_PWD=1230123

    ords_apex:
        container_name: ords
        image: container-registry.oracle.com/database/ords:22.3.2
        ports:
            - "8181:8181"
        networks:
            - apex-network
        volumes:
            - .:/opt/oracle/variables
        depends_on:
            - oracle_xe
        restart: unless-stopped

    mariadb:
        container_name: jasperdb
        image: docker.io/bitnami/mariadb:10.6
        hostname: mariadb
        networks:
            - apex-network
        ports:
            - "3306:3306"
        volumes:
            - "mariadb_data:/bitnami/mariadb"
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=bn_jasperreports
            - MARIADB_DATABASE=bitnami_jasperreports

    jasperreports:
        container_name: jasperserver
        image: docker.io/bitnami/jasperreports:8
        ports:
            - "8080:8080"
        networks:
            - apex-network
        hostname: jasper
        volumes:
            - "jasperreports_data:/bitnami/jasperreports"
        depends_on:
            - mariadb
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            - JASPERREPORTS_DATABASE_HOST=mariadb
            - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
            - JASPERREPORTS_DATABASE_USER=bn_jasperreports
            - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports

networks:
    apex-network:
        driver: bridge

volumes:
    db-volume:
    mariadb_data:
        driver: local
    jasperreports_data:
        driver: local
