SELECT ID_ARTIKL_PRODAJA,
       SIFRA,
       GRUPA_ARTIKALA_PRODAJA_ID,
       NAZIV,
       JEDINICA_MJERE_ID,
       CIJENA_S_PDVOM,
       BRISANO,
       CJENIK_ID
FROM ARTIKL_PRODAJA
WHERE NOT EXISTS(SELECT *
                 FROM PDBADMIN.NORMATIV N2
                          INNER JOIN PDBADMIN.ARTIKL_NABAVA AN2 ON AN2.ID_ARTIKL_NABAVA = N2.ARTIKL_NABAVA_ID
                 WHERE N2.ARTIKL_PRODAJA_ID = ID_ARTIKL_PRODAJA
                   AND AN2.CIJENA_BEZ_PDVA = 0)
  AND EXISTS(
        SELECT * FROM NORMATIV WHERE ARTIKL_PRODAJA_ID = ID_ARTIKL_PRODAJA)