SELECT ID_ARTIKL_PRODAJA,
       SIFRA,
       NAZIV,
       CIJENA_S_PDVOM,
       (SELECT PS.IZNOS * 100
        FROM GRUPA_ARTIKALA_PRODAJA GAP
                 INNER JOIN POREZNA_STOPA PS ON PS.ID_POREZNA_STOPA = GAP.POREZNA_STOPA_ID
        WHERE GAP.ID_GRUPA_ARTIKALA_PRODAJA = GRUPA_ARTIKALA_PRODAJA_ID)     AS POREZNASTOPA,
       (SELECT ROUND(CIJENA_S_PDVOM / (1 + IZNOS), 2)
        FROM GRUPA_ARTIKALA_PRODAJA GAP
                 INNER JOIN POREZNA_STOPA PS ON PS.ID_POREZNA_STOPA = GAP.POREZNA_STOPA_ID
        WHERE GAP.ID_GRUPA_ARTIKALA_PRODAJA = GRUPA_ARTIKALA_PRODAJA_ID)     AS CIJENA_BEZ_PDVA,
       ROUND((SELECT SUM(N3.UTROSAK * AN3.CIJENA_BEZ_PDVA)
              FROM NORMATIV N3
                       INNER JOIN ARTIKL_NABAVA AN3 ON ID_ARTIKL_NABAVA = ARTIKL_NABAVA_ID
              WHERE ARTIKL_PRODAJA_ID = ID_ARTIKL_PRODAJA),
             2)                                                              AS UKUPNI_TROSAK_MATERIJALA,
       ROUND(((SELECT CIJENA_S_PDVOM / (1 + IZNOS)
               FROM GRUPA_ARTIKALA_PRODAJA GAP
                        INNER JOIN POREZNA_STOPA PS ON PS.ID_POREZNA_STOPA = GAP.POREZNA_STOPA_ID
               WHERE GAP.ID_GRUPA_ARTIKALA_PRODAJA = GRUPA_ARTIKALA_PRODAJA_ID) /
              (SELECT SUM(N.UTROSAK * AN.CIJENA_BEZ_PDVA)
               FROM NORMATIV N
                        INNER JOIN ARTIKL_NABAVA AN ON AN.ID_ARTIKL_NABAVA = N.ARTIKL_NABAVA_ID
               WHERE N.ARTIKL_PRODAJA_ID = ID_ARTIKL_PRODAJA) - 1) * 100, 2) AS MARZA
FROM ARTIKL_PRODAJA
WHERE NOT EXISTS(SELECT *
                 FROM NORMATIV N2
                          INNER JOIN ARTIKL_NABAVA AN2 ON AN2.ID_ARTIKL_NABAVA = N2.ARTIKL_NABAVA_ID
                 WHERE N2.ARTIKL_PRODAJA_ID = ID_ARTIKL_PRODAJA
                   AND AN2.CIJENA_BEZ_PDVA = 0)
  AND EXISTS(
        SELECT * FROM NORMATIV WHERE ARTIKL_PRODAJA_ID = ID_ARTIKL_PRODAJA
    )
ORDER BY MARZA;