CREATE VIEW PDBADMIN.ARTIKLI_PRODAJE_MARZE AS
SELECT AP.ID_ARTIKL_PRODAJA,
       AP.SIFRA,
       AP.NAZIV                                                  AS NAZIV_ARTIKLA,
       GAP.NAZIV                                                 AS NAZIV_GRUPE_ARTIKLA,
       AP.CIJENA_S_PDVOM,
       ROUND(AP.CIJENA_S_PDVOM / (1 + PS.IZNOS), 2)              AS CIJENA_BEZ_PDVA,
       ROUND((AP.CIJENA_S_PDVOM / (1 + PS.IZNOS) /
              SUM(AN.CIJENA_BEZ_PDVA * N.UTROSAK) - 1) * 100, 2) AS MARZA_POSTOTAK
FROM PDBADMIN.ARTIKL_PRODAJA AP
         INNER JOIN PDBADMIN.GRUPA_ARTIKALA_PRODAJA GAP ON GAP.ID_GRUPA_ARTIKALA_PRODAJA = AP.GRUPA_ARTIKALA_PRODAJA_ID
         INNER JOIN PDBADMIN.POREZNA_STOPA PS ON PS.ID_POREZNA_STOPA = GAP.POREZNA_STOPA_ID
         INNER JOIN PDBADMIN.NORMATIV N ON AP.ID_ARTIKL_PRODAJA = N.ARTIKL_PRODAJA_ID
         INNER JOIN PDBADMIN.ARTIKL_NABAVA AN ON AN.ID_ARTIKL_NABAVA = N.ARTIKL_NABAVA_ID
WHERE AP.BRISANO = 0
  AND NOT EXISTS(SELECT *
                 FROM PDBADMIN.NORMATIV N2
                          INNER JOIN PDBADMIN.ARTIKL_NABAVA AN2 ON AN2.ID_ARTIKL_NABAVA = N2.ARTIKL_NABAVA_ID
                 WHERE N2.ARTIKL_PRODAJA_ID = AP.ID_ARTIKL_PRODAJA
                   AND AN2.CIJENA_BEZ_PDVA = 0)
GROUP BY AP.ID_ARTIKL_PRODAJA, AP.SIFRA, GAP.NAZIV, AP.NAZIV, AP.CIJENA_S_PDVOM, PS.IZNOS
/


